language: python
sudo: required
dist: xenial
python: "3.7"

# command to install dependencies
install:
  - "pip install pytest-cov coveralls"
  - "pip install -e .[test]"
  - "pip install -e .[docs]"
  - "pip install -e ."

# command to run tests
script:
  - pytest --cov=source tests
after_success:
  - coveralls